<?php
/**
 * Created by PhpStorm.
 * User: tik_squad
 * Date: 29/10/19
 * Time: 12.48
 */

namespace App;


use App\Models\Mahasiswa;
use App\Models\Predikat;
use DedeGunawan\TranskripAkademikUnsil\Services\Resolver\MysqliResolver;
use DedeGunawan\TranskripAkademikUnsil\TranskripAkademikUnsil;

class AppMysqliResolver extends MysqliResolver
{
    public function resolve()
    {
        parent::resolve(); // TODO: Change the autogenerated stub
        $this->kalibrasiPredikat();
    }

    public function kalibrasiPredikat()
    {

        $transkrip_akademik = TranskripAkademikUnsil::getInstance();
        $kelulusan = $transkrip_akademik->getKelulusan();
        $_ipk = $kelulusan->getIpk();
        $predikat = Predikat::whereRaw("IPKMin <= $_ipk and $_ipk <= IPKMax")
            ->where('ProdiID', $transkrip_akademik->getKonsentrasi()->getKodeProdi())
            ->where('KodeID', 'UNSIL')
            ->first();

        $predikatColumnMahasiswa = $predikat['Nama'];
        $predikatText = $predikat['Nama'];
        if ($this->getLanguage()=='en') {
            $predikatText = $predikat['Nama_en'];
        }

        $kelulusan->setPredikat($predikatText);
        $mahasiswa = Mahasiswa::find($transkrip_akademik->getNpm());
        $mahasiswa['predikat'] = $predikatColumnMahasiswa;
        $mahasiswa->save();

        $konsentrasi = $transkrip_akademik->getKonsentrasi();
        if (substr($konsentrasi->getKodeProdi(), 0, 2)=='21') {
            $konsentrasi->setNamaKonsentrasi("");
        }
    }
}
